# Generated by Django 3.2 on 2021-04-27 21:48

import app.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='testImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='teams/default_club.png', upload_to=app.models.testdir)),
            ],
        ),
        migrations.AlterField(
            model_name='commentcompetition',
            name='timeofpost',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='commentmatch',
            name='timeofpost',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='commentplayer',
            name='timeofpost',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='commentteam',
            name='timeofpost',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.CreateModel(
            name='CommentStaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeofpost', models.DateTimeField(default=datetime.datetime.now)),
                ('comment', models.CharField(max_length=120)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.staff')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.normaluser')),
            ],
        ),
    ]
